# Authors : Koushik , Yash , Navaz , Akhilesh
version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres_network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: bitnami/phppgadmin
    ports:
      - "8888:8080"
    networks:
      - postgres_network
    environment:
      DATABASE_HOST: postgres
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  postgres_network:
    driver: bridge

volumes:
    postgres:
